services:
  serverbrowser:
    container_name: discord-serverbrowser
    build: .
    restart: unless-stopped
    network_mode: bridge
    volumes:
      - ./config.serverbrowser.json:/app/config.json
      # - ./data:/app/data

  peerchat:
    container_name: discord-peerchat
    image: discordirc/discord-irc
    restart: unless-stopped
    network_mode: bridge
    volumes:
      - ./config.peerchat.json:/config/config.json
